lazy val root = (project in file(".")).
  settings(
    name := "MScProject",
    version := "1.0",
    scalaVersion := "2.11.8",
    resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/",
    libraryDependencies += "org.scalatest" % "scalatest_2.11" % "2.2.6",
    libraryDependencies += "com.typesafe.akka" % "akka-actor_2.11" % "2.4.7",
    libraryDependencies += "com.typesafe.akka" % "akka-remote_2.11" % "2.4.7",
    libraryDependencies += "com.typesafe.akka" % "akka-testkit_2.11" % "2.4.7",
   	libraryDependencies += "com.typesafe.akka" % "akka-typed-experimental_2.11" % "2.4.7",
    libraryDependencies += "org.scala-stm" % "scala-stm_2.11" % "0.7",
    libraryDependencies += "com.softwaremill.macwire" %% "macros" % "2.2.3" % "provided",
	libraryDependencies += "com.softwaremill.macwire" %% "util" % "2.2.3",
	libraryDependencies += "com.softwaremill.macwire" %% "proxy" % "2.2.3",
	libraryDependencies += "com.typesafe.play" % "play-json_2.11" % "2.4.6",
	libraryDependencies += "io.spray" %%  "spray-json" % "1.3.2",
	libraryDependencies += "io.spray" % "spray-httpx_2.11" % "1.3.3",
	libraryDependencies += "com.datastax.cassandra" % "cassandra-driver-core" % "3.0.0",
	libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc3.9",
	libraryDependencies += "org.nd4j" % "nd4j-native" % "0.4-rc3.9" classifier "" classifier "windows-x86_64",
	libraryDependencies += "org.datavec" % "datavec-api" % "0.4.0",
	libraryDependencies += "org.sameersingh.scalaplot" % "scalaplot" % "0.0.4",
	libraryDependencies ++= Seq(
	  "commons-io" % "commons-io" % "2.4",
	  "com.google.guava" % "guava" % "19.0",
	  "jfree" % "jfreechart" % "1.0.13",
	  "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc3.9",
	  "org.deeplearning4j" % "deeplearning4j-nlp" % "0.4-rc3.9",
	  "org.deeplearning4j" % "deeplearning4j-ui" % "0.4-rc3.9",
	  "org.jblas" % "jblas" % "1.2.4",
	  "org.nd4j" % "canova-nd4j-codec" % "0.0.0.15",
	  "org.nd4j" % "nd4j-native" % "0.4-rc3.9",
	  "org.bytedeco" % "javacv" % "1.2",
  	  "org.bytedeco" % "javacpp" % "1.2"
  	)
)